### ISSUE TITLE
llibrary is expecting signature

### ISSUE THREAD

**Issue by C0rn3j** [iLexiconn/LLibrary#56]
```
[20:39:38] [main/ERROR] [llibrary]: The mod llibrary is expecting signature ${fingerprint} for source llibrary-1.7.7-1.12.2.jar, however there is no signature matching that description
[20:39:38] [main/WARN] [LLibrary]: Detected invalid fingerprint for file llibrary-1.7.7-1.12.2.jar! You will not receive support with this tampered version of llibrary!
```

Forge 2517, MC1.12.2, LLibrary 1.7.7

**Comment by Gegy** [comment]
Fixed for LLibrary 1.7.9.

**Comment by AfterRebelion** [comment]
No, it isn't fixed.

`[Server thread/ERROR] [llibrary]: The mod llibrary is expecting signature b9f30a813bee3b9dd5652c460310cfcd54f6b7ec for source llibrary-1.7.9-1.12.2.jar, however there is no signature matching that description`

**Comment by Gegy** [comment]
Interesting.

**Comment by AfterRebelion** [comment]
For the note, the mod was downloaded from https://minecraft.curseforge.com/projects/llibrary/ , so I am pretty sure they are official files.

**Comment by Gegy** [comment]
Yep, just checked my built files and the signature is not contained. I could've sworn they were right when I checked... Will look again!

**Comment by PhoenixRiver** [comment]
I presume this will be fixed in the next version then? (I came here to submit this same bug but found this one had already been submitted :)

**Comment by Gegy** [comment]
@PhoenixRiver Yep, it will be in the next release! :)

**Comment by brisingraerowing** [comment]
Good to hear. I just noticed this myself.

**Comment by OlavWolfiken** [comment]
It's still on 1.7.18 and 1.7.19


> 	| LCHIJA | llibrary          | 1.7.18            | LLibrary-1.12.2.jar                                  | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |

> 	| LCHIJA | llibrary          | 1.7.19            | LLibrary-1.12.2.jar                                  | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
